GrandComicsDatabase/gcd-django

apps/gcd/search_indexes.py
apps/gcd/templatetags/credits.py
apps/gcd/urls.py
apps/gcd/views/search_haystack.py
static/css/gcd/default.css
templates/search/search.html

We can use facets to add further filters to search results without too much effort, it seems.
Add these step-by-step, need to check and see if further filters nicely interact and if our bit of django- and template-code is fine with it.
Start with country, which would be the most important one. Make sure it behaves nice on the production environment.
Then language (wikipedia-style), then maybe others (year ?).

add country filter to search

---

apps/gcd/forms/search.py
apps/gcd/views/search.py

as tested on beta with short feedback on main
filter for issue level reprints fills a different role, so not adding this there to avoid confusion (no existing issue level reprint links can still mean issue is a linked reprint via the stories)

add advanced search filter for sequences not being a reprint

---

apps/stddata/migrations/0003_language_native_name.py
apps/stddata/models.py
static/css/gcd/default.css
templates/gcd/status/international_stats.html

Also use it on the language stats page, where we also import cycle from future to avoid a deprecation warning.

add native name for languages

---

apps/mycomics/views.py
templates/404.html
templates/500.html
templates/mycomics/bits/issue_control.html
templates/mycomics/bits/series_control.html

When adding issues in my.comics.org, one often adds several different ones to one collection in a row. If it is not the first one, one always needs to re-select it. We now remember it and pre-select it on the issue and series pages. Maybe later also add this to selecting issues via the searches ?
Also: Point the link on 404/500 pages to github #277

mycomics: remember last added-to collection

---

apps/oi/forms/image.py
apps/oi/views.py
templates/oi/edit/list_issue_reprints.html

fixes hanged edit-views for sent back image/cover uploads
fixes editing existing reprint notes, they now get pre-filled again in the search box, currently they are twice urlencoded

fix a view forms

---

apps/oi/urls.py
apps/oi/views.py
templates/oi/edit/issue_changeset.html
templates/oi/edit/list_issue_reprints.html

undo a small recent change, and do it correctly.
It was surprisingly difficult to find the routine unquote, at least with search involving django one always finds the other way... And also surprisingly, we seemingly so far didn't need unquote at all.
also pre-full search from for existing notes under the normal issue changeset page, only using the first (of several) notes.

handle pre-fill search for existing reprint note

---

apps/gcd/forms/search.py
apps/gcd/views/search.py

As mentioned on main, it would be nice if we could show covers based the on-sale-date. 
Also observed on main, If using on-sale-date for filtering, we should also use it for sorting, and not the keydate.

use on_sale_date more in advanced search

---

apps/legacy/tools/history/__init__.py
apps/legacy/tools/history/issue.py
apps/legacy/tools/history/migrate.py
apps/legacy/tools/history/old_models.py
apps/legacy/tools/history/prepare.py
apps/legacy/tools/history/story.py

The older pull request disappeared during cleanup in my repo.
Changed migration of old logs by using two log files, one very early one and the latest before the switch to the new site.
Problem with using only the latest log is that many edits for new issues will be given to anonymous, instead of the user. The idea is now to treat all 'newer' log entries different and give much more credit to indexers than before.
The current result (running the local migrations) can be seen on beta. Another test will run on beta before even considering making one on production.
There is code on there, which is not used any more (at some point the idea was to do two runs based on two dumps, but that is not really working). Cleaning up for this once running code is not needed, and maybe someone gets a …

migration using two histories

---

apps/legacy/tools/history/issue.py
apps/legacy/tools/history/prepare.py

Need this check in the end, otherwise content which existed in 2004-X-X (the oldest dump used in the first migration run) will be assigned to the first indexer in the logs after that date, which is often wrong.

check for existing revision from first migration round

---

apps/gcd/views/details.py
templates/gcd/details/cover.html
templates/gcd/details/issue.html

The cover gallery link on the issue page under the cover now links to the appropriate point in the gallery.
#13

gallery link on issue pages goes to corresponding gallery page

---

apps/oi/import_export.py

Changed the filtering, otherwise for new brandemblems (which don't have a parent) errors arise.
When importing sequences with wrong genre, the genre will be ignored.
Some code formatting cleaning.

fix issue import for brands, ignore wrong genres

---

apps/gcd/urls.py
templates/gcd/bits/front_page_search_box.html
templates/gcd/bits/publisher_header.html
templates/gcd/bits/search_bar.html
templates/gcd/bits/series_issue_header.html
templates/gcd/bits/status_banner.html
templates/gcd/details/change_history.html
templates/gcd/details/publisher.html
templates/gcd/details/series.html
templates/gcd/index.html
templates/gcd/search/list_header.html
templates/oi/bits/compare.html
templates/oi/bits/compare_issue.html
templates/oi/bits/pending_actions.html
templates/oi/bits/reprint_type_list.html
templates/oi/bits/standard_queues.html
templates/oi/edit/compare.html
templates/oi/edit/compare_bulk_issue.html
templates/oi/edit/compare_cover.html
templates/oi/edit/compare_issue_skeletons.html
templates/oi/edit/confirm_internal.html
templates/oi/edit/confirm_reprint.html
templates/oi/edit/issue_changeset.html
templates/oi/edit/upload_cover.html
templates/oi/queues/covers.html

will take till 1.10 to be removed, warnings start with 1.8, but changes work with 1.7 as well
1) = -> == in templates 
2) use name in url-calls, not method-path

changes due to upcoming deprecations

---

apps/gcd/views/details.py

For optional columns in the series details page, the code used to check
only base issues. This change makes colums appear if a value is set for
any issue (base or variant) and be hidden if the field is set to "no"
or empty for all issues in the series.
By the way, the code stated that "These need to be numbers not True/False booleans" but that doesn't seem to be the case - I changed the .count() to .exists() and they seem to work correctly. I don't see anything in the templates that uses them as numbers, either.

Series Details: reorganize columns hiding logic

---

apps/indexer/fixtures/beta-users.yaml
apps/indexer/fixtures/users.yaml

Because otherwise you can't do things like advanced search at all.
I just looked at the default collector/collection code and copied what it was doing into the fixtures (I think).  It seems to work enough to unblock advanced search- I haven't figured out how to test mycomics locally.

Add mycomics data to initial user fixtures

---

apps/voting/views.py
requirements.txt

This does not update the production-specific modules yet.
The various commented-out modules seem to be unnecessary, so let's
take them out.  We can always put them back in if needed.
wsgiref's functionality is now covered by the standard library
Two packages needed replacing by forks for Python3:
MySQL-python => mysqlclient
python-vote-core => python3-vote-core
I removed RBTools as we're not using Review Board anymore.
Our fork of django-templatesadmin needed updating for Python 3
so it now points at that branch of our fork (which I went ahead and pushed- the change is trivial).
For everything else, I just tried installing whatever pip defaulted to and that seemed to work.

Update main requirements for Python3+Ubuntu 18.04

---

apps/gcd/models/image.py
apps/gcd/views/search.py
apps/gcd/views/search_haystack.py
apps/inducks/templatetags/flatfile.py

Since strings in python 3 are always unicode,functions are no longer named after unicode.  I left it imported `as uni` because searching/replacing that seemed like unnecessary noise.

The smart_* text functions change in Python3

---

apps/gcd/views/details.py
apps/oi/import_export.py

The only other place we use HttpResponse (writing to the stream a bit at a time) was already doing encoding.

Handle HttpResponse needing byte strings

---

apps/indexer/views.py

Because unicode is now the default but bytes are needed.
A bit silly to make its own PR, but the migrations and HttpResponse bytestring changes are logically distinct and more likely to have issues.

Fix string issues for passwords

---

apps/gcd/views/redirect.py
apps/oi/forms/award.py
apps/oi/forms/creator.py
apps/oi/forms/image.py
apps/oi/forms/publisher.py
apps/oi/import_export.py
apps/oi/models.py
apps/oi/views.py
apps/select/views.py
apps/voting/views.py

Iteration changes a bit in Python3, with `next()` now a builtin function, and `dict.keys()` removed in favor of just allowing dictionaries to be iterables on their own.  So if you need a `list` of keys, you just build one from the `dict` as an iterable.
Note that some `keys()` calls needed to produce a `set` rather than a `list`, in order to do set operations on the results.

Fix next() and keys() for Python 3

---

apps/gcd/views/search_haystack.py
requirements.txt
settings.py

This downgrades us back to the appropriate elasticsearch library for our existing version of elasticsearch.  We'll look at updating that after Python3 is deployed.
This will now index the database and run searches successfully.  It is not yet updating the index on a new write to the database, but that can be a later PR.

Get elasticsearch working for searches

---

requirements.txt

Noticed this when trying the docker way today. Github is now blocking the git protocol, so need to update. This then works with the docker file (please check any other consumption).
See https://github.blog/2021-09-01-improving-git-protocol-security-github/ .

Update from now unavailable git: protocol

---

apps/oi/models.py

I believe this will fix #557, but I'm making this change blind and without testing.

Keep bracketed text when feature migration fails

---

apps/indexer/views.py

This is needed to avoid logging out the user from the current session.

When changing password, call update_session_auth_hash()

---

apps/gcd/tests/test_series.py
apps/oi/tests/conftest.py
apps/oi/tests/test_issue_revision.py
apps/oi/tests/test_reprint_revision.py
apps/oi/tests/test_revision.py
apps/oi/tests/test_series_revision.py

- Pass test_active_base_issues_variant_count
- Pass test_classification
- Pass test_commit_deleted
- Pass test_commit_edited_dont_clear
- Follow PEP8 in conftest.py
- Prefer @pytest.fixture over @pytest.yield_fixture Yield_fixture has been deprecated for some time.

Fix some broken tests

---

templates/gcd/bits/daily_creators.html
templates/gcd/index.html

Use ```<p id="today">``` instead of ```<a name="today">``` as the element to scroll to - this fixes a discrepancy in the scroll position on Firefox. Also, hide the iframe until loading is finished, to avoid a brief flash of the previous day.

Daily creators iframe: hide and scroll after loading
